from openai import OpenAI
import os

# OpenAI API key
client = OpenAI(api_key = "OPENAI_API_KEY_HERE")


# Speech to text
audio_path = "C:\\Users\\d7oom\\Downloads\\Audio-test.m4a"
with open(audio_path, 'rb') as audio_file:
    transcript = client.audio.transcriptions.create(
        model='whisper-1',
        file=audio_file,
        response_format='text'
    )
print("Transcript:", transcript)


# Generate a response using ChatGPT
generated_text = (
    "This voice was generated by artificial intelligence, which means the code is working perfectly. "
    "Did you ever imagine that AI could actually talk? 😂"
)
print("Custom Response:", generated_text)

# Text to speech
speech_file_path = "voice-create.mp3"
response = client.audio.speech.create(
    model='tts-1',
    voice='shimmer',
    input=generated_text
)
response.stream_to_file(speech_file_path)
print("Audio Generated Successfully")
